// Array de alertas em Recife

export const alerts = [
    {
      latitude: -8.0476,
      longitude: -34.8770,
      title: 'Iluminação Precária',
      description: 'A rua está mal iluminada à noite, criando risco de segurança. Recomenda-se cautela ao passar.',
      type: 'Condições da Rua',
      upvotes: 12,
      downvotes: 3,
      createdBy: 'Usuário123',
      timestamp: '2025-04-01T12:00:00Z',
      duration: 'Permanente',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0495,
      longitude: -34.8777,
      title: 'Acidente de Trânsito',
      description: 'Houve um acidente envolvendo dois veículos na Avenida Boa Viagem. O trânsito está congestionado.',
      type: 'Incidentes de Trânsito',
      upvotes: 15,
      downvotes: 2,
      createdBy: 'Usuário789',
      timestamp: '2025-04-01T14:30:00Z',
      duration: '2 horas',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0474,
      longitude: -34.8912,
      title: 'Deslizamento de Terra',
      description: 'A chuva intensa causou um deslizamento de terra na área da Avenida Rio Branco. A via está bloqueada.',
      type: 'Incidentes de Trânsito',
      upvotes: 20,
      downvotes: 0,
      createdBy: 'Sistema',
      timestamp: '2025-04-01T15:00:00Z',
      duration: 'Permanente',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0261,
      longitude: -34.8781,
      title: 'Alagamento',
      description: 'A Rua do Sol está alagada devido às chuvas intensas, dificultando o tráfego de veículos e pedestres.',
      type: 'Condições Climáticas',
      upvotes: 25,
      downvotes: 5,
      createdBy: 'Usuário321',
      timestamp: '2025-04-01T16:00:00Z',
      duration: '2 horas',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0293,
      longitude: -34.8915,
      title: 'Feira na Rua',
      description: 'Há uma feira na Rua da Aurora, causando bloqueio parcial da via. Trânsito complicado.',
      type: 'Outros',
      upvotes: 10,
      downvotes: 1,
      createdBy: 'Usuário654',
      timestamp: '2025-04-01T17:30:00Z',
      duration: '4 horas',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0274,
      longitude: -34.8820,
      title: 'Caminhão Bloqueando a Via',
      description: 'Caminhão de carga bloqueia a Rua do Bom Jesus. O tráfego está restrito para veículos pequenos.',
      type: 'Incidentes de Trânsito',
      upvotes: 5,
      downvotes: 0,
      createdBy: 'Usuário987',
      timestamp: '2025-04-01T18:00:00Z',
      duration: '1 hora',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0284,
      longitude: -34.8772,
      title: 'Presença de Animais na Rua',
      description: 'Há vários animais soltos na Rua do Apolo, criando risco para pedestres e motoristas.',
      type: 'Segurança',
      upvotes: 3,
      downvotes: 1,
      createdBy: 'Usuário234',
      timestamp: '2025-04-01T19:00:00Z',
      duration: 'Permanente',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0299,
      longitude: -34.8725,
      title: 'Obra na Rua',
      description: 'Há uma grande obra na Avenida Conselheiro Aguiar. O tráfego está sendo desviado.',
      type: 'Outros',
      upvotes: 18,
      downvotes: 4,
      createdBy: 'Usuário555',
      timestamp: '2025-04-01T20:00:00Z',
      duration: '1 semana',
      photo: require('./images/alert.png'),
    },
    {
      latitude: -8.0456,
      longitude: -34.8765,
      title: 'Pavimentação Danificada',
      description: 'A pavimentação da Rua Marquês de Olinda está danificada, dificultando a circulação de pedestres e veículos.',
      type: 'Condições da Rua',
      upvotes: 22,
      downvotes: 6,
      createdBy: 'Usuário111',
      timestamp: '2025-04-01T21:30:00Z',
      duration: 'Permanente',
      photo: require('./images/alert.png'),
    },
  ];
  